### ISSUE TITLE
Scope: publish_actions not working

### ISSUE THREAD

**Issue by phongyu** [zyra/ng2-facebook-sdk#66]
Hi, 
I am trying to share canvas to Facebook, 
I followed: https://github.com/lukasz-madon/heroesgenerator to implement the function in component

shareFacebook() {
    var canvas = $('#myCanvas').get(0);
    var data = canvas.toDataURL("image/png");
    var encodedPng = data.substring(data.indexOf(',') + 1, data.length);
    var decodedPng = Base64Binary.decode(encodedPng);

    const options: LoginOptions = {
      scope: 'publish_actions',
      return_scopes: true,
      enable_profile_selector: true
    };
    this.fb.login(options).then((response: any) => {
      this.postImageToFacebook(response.authResponse.accessToken, "canvasImg", "image/png", decodedPng, "www.heroesgenerator.com");
    });
}

I got error: 
{
   "error": {
      "message": "(#200) Requires extended permission: publish_actions",
      "type": "OAuthException",
      "code": 200,
      "fbtrace_id": "CH3fu/EmGwh"
   }
}
the Facebook didn't login with scope 'publish_actions'

Any Suggestion is appreciated

**Comment by ihadeed** [comment]
You're getting this issue because `publish_actions` is an extended permission that you need to get approval for. You should use a test version of your Facebook app to test this out.

See the Review section here for more details: https://developers.facebook.com/docs/facebook-login/permissions/#reference-publish_actions
